# Generated by Django 5.0.7 on 2024-10-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devarch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apropos',
            options={'verbose_name': 'Apropos', 'verbose_name_plural': 'Apropos'},
        ),
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name': 'Avis', 'verbose_name_plural': 'Avis'},
        ),
    ]
